/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 deskScene.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/deskScene.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.kovrik_blinn1_0001.geometry} material={materials.blinn1} position={[1.596, 3.21, -4.938]} />
      <mesh geometry={nodes.kovrik_blinn1_0_1.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.kovrik_blinn1_0_2.geometry} material={materials.Crystal} />
      <mesh geometry={nodes.kovrik_blinn1_0_3.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.kovrik_blinn1_0_4.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.kovrik_blinn1_0_5.geometry} material={materials.Base_Material} />
      <mesh geometry={nodes.kovrik_blinn1_0_6.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.kovrik_blinn1_0_7.geometry} material={materials['plant.001']} />
      <mesh geometry={nodes.kovrik_blinn1_0_8.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.kovrik_blinn1_0_9.geometry} material={materials.emissive} />
    </group>
  )
}

useGLTF.preload('/deskScene.glb')
