/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 deskScene.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'
import { EffectComposer, SelectiveBloom } from '@react-three/postprocessing';
import { BlendFunction } from "postprocessing";

export function Scene(props) {
    const matcapTexture = useTexture('/images/textures/mat1.png');
    const screensRef= useRef();
    const crystalRef = useRef();
    // const shroomRef = useRef();
    const treeMaterial = new THREE.MeshPhongMaterial({color: '#d90429'})

    const bodyMaterial = new THREE.MeshPhongMaterial({
        map: matcapTexture
    });

    const { nodes, materials } = useGLTF('/models/deskScene.glb')

    return (
        <group {...props} dispose={null}>
            <EffectComposer>
                <SelectiveBloom
                selection={[screensRef, crystalRef]}
                intensity={0.3} // Strength of the bloom
                luminanceThreshold={.3} // Minimum luminance needed
                luminanceSmoothing={.9} // Smooth transition
                blendFunction={BlendFunction.ADD} // How it blends
                />
            </EffectComposer>
            <mesh geometry={nodes.kovrik_blinn1_0001.geometry} material={materials.blinn1} position={[1.596, 3.21, -4.938]} />
            <mesh geometry={nodes.kovrik_blinn1_0_1.geometry} material={materials.blinn1} />
            <mesh ref={crystalRef} geometry={nodes.kovrik_blinn1_0_2.geometry} material={materials.Crystal} />
            <mesh geometry={nodes.kovrik_blinn1_0_3.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.kovrik_blinn1_0_4.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.kovrik_blinn1_0_5.geometry} material={materials.Base_Material} />
            <mesh geometry={nodes.kovrik_blinn1_0_6.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.kovrik_blinn1_0_7.geometry} material={materials['plant.001']} />
            <mesh geometry={nodes.kovrik_blinn1_0_8.geometry} material={materials['Material.003']} />
            <mesh ref={screensRef} geometry={nodes.kovrik_blinn1_0_9.geometry} material={materials.emissive} />
        </group>
    )
}

useGLTF.preload('/models/deskScene.glb')
