/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wolfIslandScene.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Island(props) {
  const { nodes, materials } = useGLTF('models/wolfIslandScene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.084, 0.106, -66.716]} rotation={[Math.PI, 0, 0]} scale={[1.932, 1.488, 1.17]}>
        <mesh geometry={nodes.Icosphere023.geometry} material={materials.darkGreen} />
        <mesh geometry={nodes.Icosphere023_1.geometry} material={materials.bark} />
        <mesh geometry={nodes.Icosphere023_2.geometry} material={materials.grass} />
        <mesh geometry={nodes.Icosphere023_3.geometry} material={materials.stone} />
      </group>
    </group>
  )
}

useGLTF.preload('models/wolfIslandScene.glb')
